# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 423)
        MainWindow.setBaseSize(QtCore.QSize(200, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowOpacity(3.0)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sel_baud_label = QtWidgets.QLabel(self.centralwidget)
        self.sel_baud_label.setObjectName("sel_baud_label")
        self.gridLayout.addWidget(self.sel_baud_label, 1, 0, 1, 1)
        self.sel_porta_label = QtWidgets.QLabel(self.centralwidget)
        self.sel_porta_label.setObjectName("sel_porta_label")
        self.gridLayout.addWidget(self.sel_porta_label, 0, 0, 1, 3)
        self.porta_radiobutton = QtWidgets.QRadioButton(self.centralwidget)
        self.porta_radiobutton.setCheckable(True)
        self.porta_radiobutton.setChecked(False)
        self.porta_radiobutton.setObjectName("porta_radiobutton")
        self.gridLayout.addWidget(self.porta_radiobutton, 0, 3, 1, 2)
        self.inicia = QtWidgets.QPushButton(self.centralwidget)
        self.inicia.setCheckable(False)
        self.inicia.setAutoDefault(False)
        self.inicia.setDefault(False)
        self.inicia.setFlat(False)
        self.inicia.setObjectName("inicia")
        self.gridLayout.addWidget(self.inicia, 2, 0, 1, 2)
        self.exibe_dados = QtWidgets.QTextBrowser(self.centralwidget)
        self.exibe_dados.setBaseSize(QtCore.QSize(200, 200))
        self.exibe_dados.setObjectName("exibe_dados")
        self.gridLayout.addWidget(self.exibe_dados, 5, 0, 1, 8)
        self.parar_rol_radioB = QtWidgets.QRadioButton(self.centralwidget)
        self.parar_rol_radioB.setObjectName("parar_rol_radioB")
        self.buttonGroup_rol = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_rol.setObjectName("buttonGroup_rol")
        self.buttonGroup_rol.addButton(self.parar_rol_radioB)
        self.gridLayout.addWidget(self.parar_rol_radioB, 6, 3, 1, 3)
        self.baud_115200 = QtWidgets.QRadioButton(self.centralwidget)
        self.baud_115200.setChecked(True)
        self.baud_115200.setObjectName("baud_115200")
        self.buttonGroup_baud = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_baud.setObjectName("buttonGroup_baud")
        self.buttonGroup_baud.addButton(self.baud_115200)
        self.gridLayout.addWidget(self.baud_115200, 1, 7, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.kp_label = QtWidgets.QLabel(self.centralwidget)
        self.kp_label.setObjectName("kp_label")
        self.gridLayout_2.addWidget(self.kp_label, 0, 0, 1, 1)
        self.entra_kp = QtWidgets.QLineEdit(self.centralwidget)
        self.entra_kp.setObjectName("entra_kp")
        self.gridLayout_2.addWidget(self.entra_kp, 0, 1, 1, 1)
        self.entra_ki = QtWidgets.QLineEdit(self.centralwidget)
        self.entra_ki.setObjectName("entra_ki")
        self.gridLayout_2.addWidget(self.entra_ki, 1, 1, 1, 1)
        self.kd_label = QtWidgets.QLabel(self.centralwidget)
        self.kd_label.setObjectName("kd_label")
        self.gridLayout_2.addWidget(self.kd_label, 2, 0, 1, 1)
        self.entra_kd = QtWidgets.QLineEdit(self.centralwidget)
        self.entra_kd.setObjectName("entra_kd")
        self.gridLayout_2.addWidget(self.entra_kd, 2, 1, 1, 1)
        self.ki_label = QtWidgets.QLabel(self.centralwidget)
        self.ki_label.setObjectName("ki_label")
        self.gridLayout_2.addWidget(self.ki_label, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 8, 1, 2)
        self.baud_9600 = QtWidgets.QRadioButton(self.centralwidget)
        self.baud_9600.setObjectName("baud_9600")
        self.buttonGroup_baud.addButton(self.baud_9600)
        self.gridLayout.addWidget(self.baud_9600, 1, 4, 1, 1)
        self.texto_label = QtWidgets.QLabel(self.centralwidget)
        self.texto_label.setObjectName("texto_label")
        self.gridLayout.addWidget(self.texto_label, 4, 0, 1, 8)
        self.baud_38400 = QtWidgets.QRadioButton(self.centralwidget)
        self.baud_38400.setObjectName("baud_38400")
        self.buttonGroup_baud.addButton(self.baud_38400)
        self.gridLayout.addWidget(self.baud_38400, 1, 5, 1, 1)
        self.baud_57600 = QtWidgets.QRadioButton(self.centralwidget)
        self.baud_57600.setObjectName("baud_57600")
        self.buttonGroup_baud.addButton(self.baud_57600)
        self.gridLayout.addWidget(self.baud_57600, 1, 6, 1, 1)
        self.graf_agora = QtWidgets.QPushButton(self.centralwidget)
        self.graf_agora.setObjectName("graf_agora")
        self.gridLayout.addWidget(self.graf_agora, 3, 0, 1, 5)
        self.auto_rol_radioB = QtWidgets.QRadioButton(self.centralwidget)
        self.auto_rol_radioB.setChecked(True)
        self.auto_rol_radioB.setObjectName("auto_rol_radioB")
        self.buttonGroup_rol.addButton(self.auto_rol_radioB)
        self.gridLayout.addWidget(self.auto_rol_radioB, 6, 0, 1, 3)
        self.graf = QtWidgets.QPushButton(self.centralwidget)
        self.graf.setObjectName("graf")
        self.gridLayout.addWidget(self.graf, 3, 5, 1, 2)
        self.conectado_label = QtWidgets.QLabel(self.centralwidget)
        self.conectado_label.setObjectName("conectado_label")
        self.gridLayout.addWidget(self.conectado_label, 7, 0, 1, 2)
        self.baud_230400 = QtWidgets.QRadioButton(self.centralwidget)
        self.baud_230400.setObjectName("baud_230400")
        self.buttonGroup_baud.addButton(self.baud_230400)
        self.gridLayout.addWidget(self.baud_230400, 1, 8, 1, 1)
        self.baud_4800 = QtWidgets.QRadioButton(self.centralwidget)
        self.baud_4800.setObjectName("baud_4800")
        self.buttonGroup_baud.addButton(self.baud_4800)
        self.gridLayout.addWidget(self.baud_4800, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 3, 1, 1)
        self.exibe_connect = QtWidgets.QLineEdit(self.centralwidget)
        self.exibe_connect.setObjectName("exibe_connect")
        self.gridLayout.addWidget(self.exibe_connect, 7, 2, 1, 4)
        self.sel_porta_label.raise_()
        self.baud_57600.raise_()
        self.baud_9600.raise_()
        self.baud_115200.raise_()
        self.porta_radiobutton.raise_()
        self.sel_baud_label.raise_()
        self.baud_38400.raise_()
        self.exibe_dados.raise_()
        self.exibe_connect.raise_()
        self.graf_agora.raise_()
        self.inicia.raise_()
        self.texto_label.raise_()
        self.conectado_label.raise_()
        self.auto_rol_radioB.raise_()
        self.parar_rol_radioB.raise_()
        self.ki_label.raise_()
        self.graf.raise_()
        self.pushButton.raise_()
        self.baud_230400.raise_()
        self.baud_4800.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 21))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFechar = QtWidgets.QMenu(self.menubar)
        self.menuFechar.setObjectName("menuFechar")
        self.menuAtualizar_Portas = QtWidgets.QMenu(self.menubar)
        self.menuAtualizar_Portas.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.menuAtualizar_Portas.setTearOffEnabled(False)
        self.menuAtualizar_Portas.setObjectName("menuAtualizar_Portas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionReiniciar = QtWidgets.QAction(MainWindow)
        self.actionReiniciar.setObjectName("actionReiniciar")
        self.actionReiniciar.triggered.connect(self.reiniciar)

        self.actionAtualizar_portas = QtWidgets.QAction(MainWindow)
        self.actionAtualizar_portas.setObjectName("actionAtualizar_portas")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionAtualizar = QtWidgets.QAction(MainWindow)
        self.actionAtualizar.setObjectName("actionAtualizar")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.menuFechar.addAction(self.actionSalvar)
        self.menuFechar.addAction(self.actionReiniciar)
        self.menuFechar.addAction(self.actionSair)
        self.menuAtualizar_Portas.addAction(self.actionAtualizar)
        self.menubar.addAction(self.menuFechar.menuAction())
        self.menubar.addAction(self.menuAtualizar_Portas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def reiniciar(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setText("Tem certeza?")
        msg.setWindowTitle("Reiniciando...")
        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.Cancel)
        botao_sim = msg.button(QMessageBox.Yes)
        botao_sim.setText('Sim')
        botao_cancela = msg.button(QMessageBox.Cancel)
        botao_cancela.setText('Cancelar')
        msg.exec_()
        if msg.clickedButton() == botao_sim:
            python = sys.executable
            os.execl(python, python, *sys.argv)
        elif msg.clickedButton() == botao_cancela:
            return None

    # NO pressed

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Controle PID"))
        self.sel_baud_label.setText(_translate("MainWindow", "Baudrate:"))
        self.sel_porta_label.setText(_translate("MainWindow", "Selecione a porta:"))
        self.porta_radiobutton.setText(_translate("MainWindow", "R"))
        self.inicia.setText(_translate("MainWindow", "Iniciar leitura"))
        self.parar_rol_radioB.setText(_translate("MainWindow", "Parar auto rolagem"))
        self.baud_115200.setText(_translate("MainWindow", "115200"))
        self.kp_label.setText(_translate("MainWindow", "Kp"))
        self.kd_label.setText(_translate("MainWindow", "Kd"))
        self.ki_label.setText(_translate("MainWindow", "Ki"))
        self.baud_9600.setText(_translate("MainWindow", "9600"))
        self.texto_label.setText(_translate("MainWindow", "Set point      soma erro     LDR_valor        r          kp       ki       kd"))
        self.baud_38400.setText(_translate("MainWindow", "38400"))
        self.baud_57600.setText(_translate("MainWindow", "57600"))
        self.graf_agora.setText(_translate("MainWindow", "Exibir gráfico em tempo real"))
        self.auto_rol_radioB.setText(_translate("MainWindow", "Auto rolagem"))
        self.graf.setText(_translate("MainWindow", "Exibir gráfico"))
        self.conectado_label.setText(_translate("MainWindow", "Conectado a:"))
        self.baud_230400.setText(_translate("MainWindow", "230400"))
        self.baud_4800.setText(_translate("MainWindow", "4800"))
        self.pushButton.setText(_translate("MainWindow", "Salvar"))
        self.menuFechar.setTitle(_translate("MainWindow", "Menu"))
        self.menuAtualizar_Portas.setTitle(_translate("MainWindow", "Porta serial"))
        self.actionReiniciar.setText(_translate("MainWindow", "Reiniciar"))
        self.actionAtualizar_portas.setText(_translate("MainWindow", "Atualizar portas"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
